name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Test with Swift
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: swift test
        run: swift test
